Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile'